#server:
#  port: 8888

msg1: 'hello \n world'  #单引号忽略转义字符
msg2: "hello \n world"  #双引号识别转义字符

name: zhangsan

#对象
person:
  name: ${name}  #参数引用   #zhangsan
  age: 20

#数组
address:
  - beijing
  - shanghai

#数组行内写法
address2: [beijing,shanghai]


#---
#server:
#  port: 8081
#
#spring:
#  profiles: dev
#---
#server:
#  port: 8082
#
#spring:
#  profiles: pro
#---
#server:
#  port: 8083
#
#spring:
#  profiles: test
#---
#
#spring:
#  profiles:
#    active: dev